site_name: fluxie

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - fluxie

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: guide.md
  - API: api.md
  - Hall of Fame: hall_of_fame.md
  - Credit: credits.md