[build-system]
requires = ["hatchling >= 1.26", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "fluxie"
dynamic = ["version"]
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "xarray>=2023.08",
  "h5py",
  "h5netcdf",
  "geopandas",
  "PyYAML",
]
requires-python = ">=3.8"

[tool.hatch.version]
source = "uv-dynamic-versioning"

authors = [
  {name = "Alexandre Danjou", email = "alexandre.danjou@bristol.ac.uk"},
  {name = "Alice Ramsden", email = "alice.ramsden@metoffice.gov.uk"},
  {name = "Daniela Brito Melo", email = "daniela.britomelo@empa.ch"},
  {name = "Hélène De Longueville", email = "helene.delongueville@bristol.ac.uk"},
  {name = "Lionel Constantin", email = "lionel.constantin@empa.ch"},
  {name = "Stephan Henne", email = "stephan.henne@empa.ch"},
  {name = "Joël Thanwerdas", email = "joel.thanwerdas@empa.ch"},
  {name = "Peter Andrews", email = "peter.andrews@metoffice.gov.uk"},
  {name = "Valentin Bruch"},
  {name = "Fabian Maier", email = "fmaier@bgc-jena.mpg.de"},
  {name = "Leah Herrfurth", email = "lherr@bgc-jena.mpg.de"},
]
maintainers = [
  {name = "Alice Ramsden", email = "alice.ramsden@metoffice.gov.uk"},
  {name = "Daniela Brito Melo", email = "daniela.britomelo@empa.ch"},
  {name = "Lionel Constantin", email = "lionel.constantin@empa.ch"},
]
description = "Inverse modelling intercomparison tool"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["inverse modelling", "greenhouse gases", "emission fluxes", "mole fractions"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
]


[project.urls]
Homepage = "https://github.com/openghg/fluxie"
Documentation = "https://github.com/openghg/fluxie/blob/devel/README.md"
Repository = "https://github.com/openghg/fluxie"
"Bug Tracker" = "https://github.com/openghg/fluxie/issues"
"PARIS project" = "https://horizoneurope-paris.eu/"


