[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "fluxie"
version = "0.0.1"
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "xarray>=2023.08",
  "h5py",
  "h5netcdf",
  "geopandas",
  "PyYAML",
]
requires-python = ">=3.8"
authors = [
  {name = "FLUXIE developers"},
]
maintainers = [
  {name = "FLUXIE maintainers"},
]
description = "Inverse modelling intercomparison tool"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["inverse modelling", "greenhouse gases", "emission fluxes", "mole fractions"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
]


[project.urls]
Homepage = "https://github.com/openghg/fluxie"
Documentation = "https://github.com/openghg/fluxie/blob/devel/README.md"
Repository = "https://github.com/openghg/fluxie"
"Bug Tracker" = "https://github.com/openghg/fluxie/issues"
"PARIS project" = "https://horizoneurope-paris.eu/"


